name: Build & Push Docker image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Clona el repo
      - uses: actions/checkout@v4

      # 2) Habilita emulación (soporta AMD/ARM si lo necesitas)
      - uses: docker/setup-qemu-action@v3

      # 3) Prepara Docker Buildx
      - uses: docker/setup-buildx-action@v3

      # 4) Inicia sesión en GHCR (GitHub Container Registry)
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5) Compila y sube la imagen “latest”
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile      # ruta a tu Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
